<?php return array (
  'energy_static_release_bl' => '0.01',
  'energy_ky_release_bl' => '0.8',
  'energy_xfjf_release_bl' => '0',
  'energy_gyjjf_release_bl' => '0.2',
  'energy_team_reward_bl' => '0.05',
  'energy_recommend_1_reward_bl' => '0',
  'energy_recommend_2_reward_bl' => '0',
  'energy_community_50000_reward_bl' => '0',
  'energy_community_40000_reward_bl' => '0',
  'energy_community_30000_reward_bl' => '0',
  'energy_community_20000_reward_bl' => '0',
  'energy_community_10000_reward_bl' => '0',
  'energy_zk_bl' => '0',
  'energy_jiasu_bl' => '0.2',
  'energy_captain_bl' => '0.02',
  'share_star_reward' => '0.1',
  'energy_head_lv1' => '0.4',
  'energy_head_lv2' => '0.35',
  'energy_head_lv3' => '0.3',
  'energy_switch' => '0',
);