<?php return array (
  'trade_release_status' => '0',
  'kuangji_release_bl' => '0.2',
  'kuangji_redeem_30_bl' => '0.3',
  'kuangji_redeem_60_bl' => '0.5',
  'kuangji_redeem_90_bl' => 0.3,
  'kuangji_redeem_switch' => '0',
  'kuangji_flexible_price' => '500000',
  'kuangji_flexible_suanli_bl' => '0.001',
  'kuangji_flexible_min' => '1',
  'kuangji_flexible_max' => '50000',
  'kuangji_cash_switch' => '0',
  'kuangji_linghuo_redeem_switch' => '0',
  'kuangji_zhiji_rate' => '0.03',
);